{
 "title": "IoT Workshop",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "sensor", "label": "Sensor", "query": "sensor.*" }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "format": "farenheit",
   "valueName": "avg",
   "targets": [
    {
     "target": "averageSeries(sensor.$sensor.temp_f)"
    }
   ]
  },
  {
   "title": "Heat Index",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "format": "farenheit",
   "valueName": "avg",
   "targets": [
    {
     "target": "averageSeries(sensor.$sensor.heat_index_f)"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "averageSeries(sensor.$sensor.humidity)"
    }
   ]
  },
  {
   "title": "DHT11",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sensor.$sensor.temp_f, 1), '$', ' Temperature')"
    },
    {
     "target": "aliasSub(aliasByNode(sensor.$sensor.heat_index_f, 1), '$', ' Heat Index')"
    },
    {
     "target": "aliasSub(aliasByNode(sensor.$sensor.humidity, 1), '$', ' Humidity')"
    }
   ]
  }
 ]
}